/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Router;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author VanPhu
 */
public class Minitor extends javax.swing.JFrame {

    /**
     * Creates new form Minitor
     */
    public static String msg = "";
    static ServerSocket ss;
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;

    public Minitor() {
        initComponents();
        System.out.println("Thong Bao" + msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_msg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Arean = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_msg.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        text_msg.setText("Info");

        txt_Arean.setColumns(20);
        txt_Arean.setRows(5);
        jScrollPane1.setViewportView(txt_Arean);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(text_msg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(text_msg)
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Minitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Minitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Minitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Minitor().setVisible(true);
            }
        });
        DataOutputStream dos = null;
        DataInputStream dis = null;
        String msgin = "";
//        try {
//            ServerSocket ss = new ServerSocket(1205);
//            Socket s = ss.accept();
//            System.out.println("Monitor started.");
//            dis = new DataInputStream(s.getInputStream());
//            System.out.println("Info" + dis.readUTF());
//            JOptionPane.showMessageDialog(null, dis.readUTF());
//            text_msg.setText(dis.readUTF());
//            msg = dis.readUTF();
//            while (!msgin.equals("exit")) {
//                msgin = dis.readUTF();
//                txt_Arean.setText(txt_Arean.getText().trim() + "\n  \t" + msgin);
//            }
//        } catch (Exception e) {
//            System.out.println("Cannot Connect Monitor!" + e.getMessage());
//            System.exit(0);
//        }
        try {
            ServerSocket ss = new ServerSocket(1205);
            Socket s = ss.accept();
            txt_Arean.setText("Monitor started.");
            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());
            while (!msgin.equals("exit")) {
                msgin = din.readUTF();
                txt_Arean.setText(txt_Arean.getText().trim() + "\n" + msgin);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel text_msg;
    private static javax.swing.JTextArea txt_Arean;
    // End of variables declaration//GEN-END:variables
}
